### ISSUE TITLE
The plugin only played a crash game once "/alwayscratch+playername"

### ISSUE THREAD

**Issue by PaiAleMon** [goteusz-maszyk/ClientCrasher-Fabric#1] opened 2024-01-11 16:40 UTC
In the fabric version of Minecraft 1.20.1, after entering "/alwayscratch+playername".
Cheet will only crash the game once. After restarting the game,
Cheat can still access the server by joining the server again. And there was no crash game
The plugin only played a crash game once. No effect always crash

**Comment by goteusz-maszyk** [comment] 2024-03-22 22:19
Are you sure you're running `/alwayscrash <nick>`? I can't reproduce this issue.

**Comment by goteusz-maszyk** [comment] 2024-05-11 16:32
Duplicate of #4

**Closed as not planned by goteusz-maszyk** 2024-05-11 16:32 UTC
